name: CI/CD Pipeline - Tomcat Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest 

    steps:

      # 1. Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. Build WAR file
      - name: Build Application
        run: mvn clean package -DskipTests

# 4. Copy WAR to Ubuntu user's home directory
      - name: Copy WAR to Tomcat Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USER }}
          key: ${{ secrets.TOMCAT_SSH_KEY }}
          source: "target/*.war"
          target: "/home/ubuntu/"
          strip_components: 1

  
      - name: Deploy WAR and Restart Tomcat
        uses: appleboy/ssh-action@v1
        with:
              host: ${{ secrets.TOMCAT_HOST }}
              username: ${{ secrets.TOMCAT_USER }}
              key: ${{ secrets.TOMCAT_SSH_KEY }}
              script: |
                 sudo mv /home/ubuntu/*.war /root/tomcat/apache-tomcat-10.1.59/webapps/

                  sudo /root/tomcat/apache-tomcat-10.1.59/bin/shutdown.sh || true
                  sleep 5
                 sudo /root/tomcat/apache-tomcat-10.1.59/bin/startup.sh
